### ISSUE TITLE
Comment highlighting

### ISSUE THREAD

**Issue by Jeff-Birt** [RickCarlino/vscode-forth#1]
Hello, just found your extension today. One oddity I have found is that most things, including comments are not highlighted. It is not due to a color theme setting as I tried overriding that setting on the VS Code default theme and can change the comment color but not for forth files (.fs in my case).

The only syntax I see a color highlight for is a double quote, i.e.  ." my text"

Comments are properly recognized it seems and I can comment and uncomment both blocks and lines with the correct syntax using Ctrl+/ and Alt+Shft+A but the comments are not highlighted.

I have tried to make since of the interaction between the language grammar tokenization scope and the theme colorization but I'm still left confused. Most explanations I have found seem to talk around the issue rather than explaining how it should work.

**Comment by Jeff-Birt** [comment]
OK, partially answering my own question now. If I understand correctly the vscode-forth/syntaxes/forth.tmLanguage.json file is what controls what get highlighted. Since only keywords and strings are defined there that is all that will get highlighted.

Now to learn more about TextMate...

**Comment by RickCarlino** [comment]
@Jeff-Birt Greetings! You are correct, the `tmLanguage` controls all the highlighting. I have not touched this project in over a year (Forth is a hobby for me, using it outside of work entirely). If you do managed to find a fix, let me know or submit a PR and I can re-publish.

Thanks!
